import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Horizon - Paper journey</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <h1>change locale</h1>
        
      </div>
      <main>
        <h1>Welcome</h1>
      </main>

    </div>
  )
}

export default Home
